apiVersion: v1
kind: Service
metadata:
  name: modern-service
spec:
  selector:
    app: modern-musician
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer