apiVersion: v1
kind: Service
metadata:
  name: known-template-service
spec:
  selector:
    app: known-template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer