apiVersion: v1
kind: Service
metadata:
  name: highway-service
spec:
  selector:
    app: highway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort